# Generated by Django 5.2 on 2025-05-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationgroup",
            name="slots_remaining",
            field=models.IntegerField(default=0),
        ),
    ]
