# Generated by Django 5.2 on 2025-05-05 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_registrationgroup_slots_remaining"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="group",
        ),
        migrations.AddField(
            model_name="customuser",
            name="registration_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.registrationgroup",
            ),
        ),
    ]
