# Generated by Django 5.2 on 2025-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_customuser_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationgroup",
            name="serial_prefix",
            field=models.CharField(
                blank=True, help_text="E.g., S001 or H002", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="registrationgroup",
            name="state_code",
            field=models.CharField(
                blank=True, help_text="E.g., LA, AB, KD", max_length=3
            ),
        ),
    ]
