# Generated by Django 5.2 on 2025-05-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_studentslot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationgroup",
            name="proof_of_payment",
            field=models.FileField(blank=True, null=True, upload_to="payment_proofs/"),
        ),
    ]
