# Generated by Django 5.2 on 2025-05-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_registrationgroup_proof_of_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrationgroup",
            old_name="date_registered",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="registrationgroup",
            name="group_type",
        ),
        migrations.RemoveField(
            model_name="registrationgroup",
            name="proof_of_payment",
        ),
        migrations.RemoveField(
            model_name="registrationgroup",
            name="slots_applied",
        ),
        migrations.RemoveField(
            model_name="registrationgroup",
            name="slots_remaining",
        ),
        migrations.AddField(
            model_name="registrationgroup",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("school", "School"),
                    ("home", "Home"),
                    ("referral", "Referral"),
                ],
                default="school",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="registrationgroup",
            name="email",
            field=models.EmailField(default="email@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="registrationgroup",
            name="location",
            field=models.CharField(default="Ikeja", max_length=100),
        ),
        migrations.AddField(
            model_name="registrationgroup",
            name="name",
            field=models.CharField(default="John Ken", max_length=100),
        ),
        migrations.AddField(
            model_name="registrationgroup",
            name="referral_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="registrationgroup",
            name="slots",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="registrationgroup",
            name="account_details",
            field=models.TextField(blank=True, default="Not provided"),
        ),
        migrations.AlterField(
            model_name="registrationgroup",
            name="serial_prefix",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="registrationgroup",
            name="state",
            field=models.CharField(default="Lagos", max_length=100),
        ),
        migrations.AlterField(
            model_name="registrationgroup",
            name="state_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
