# Generated by Django 5.2 on 2025-05-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_rename_date_registered_registrationgroup_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrationgroup",
            old_name="slots",
            new_name="slots_applied",
        ),
        migrations.AddField(
            model_name="registrationgroup",
            name="slots_remaining",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
