# Generated by Django 5.2 on 2025-05-12 12:26

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_rename_slots_registrationgroup_slots_applied_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
    ]
