# Generated by Django 5.2 on 2025-05-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
