# Generated by Django 5.2.2 on 2025-06-12 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0004_studentattendancesummary_teacherlessonsummary"),
        ("users", "0013_customuser_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="ole_class_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ole_students",
                to="teachers.oleclasslevel",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ole_subjects",
            field=models.ManyToManyField(
                blank=True, related_name="ole_students", to="teachers.olesubject"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                    ("ole_student", "Ole Student"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OleStudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="teachers.oleclasslevel",
                    ),
                ),
                ("subjects", models.ManyToManyField(to="teachers.olesubject")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ole_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
