# Generated by Django 5.2.2 on 2025-06-14 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0005_teacherinterview"),
        ("users", "0015_olestudentsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="OleStudentSubjectAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ole_class_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="teachers.oleclasslevel",
                    ),
                ),
                ("ole_subjects", models.ManyToManyField(to="teachers.olesubject")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
