# Generated by Django 5.2.3 on 2025-06-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_olestudentsubjectaccess"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("registration_attempt", "Registration Attempt"),
                            ("user_created", "User Created"),
                            ("subject_assigned", "Subject Assigned"),
                            ("payment_initialized", "Payment Initialized"),
                            ("existing_subscription", "Existing Subscription"),
                            ("error", "Error"),
                        ],
                        max_length=50,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("details", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("duration_days", models.IntegerField()),
            ],
        ),
    ]
