# Generated by Django 5.2.3 on 2025-06-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_adminactionlog_subscriptionplan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="olestudentsubjectaccess",
            old_name="student",
            new_name="ole_student",
        ),
    ]
