# Generated by Django 5.2.3 on 2025-06-23 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0009_attendancelog_left_at_olelesson_completed_and_more"),
        ("users", "0018_rename_student_olestudentsubjectaccess_ole_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminactionlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Admin Action Log",
                "verbose_name_plural": "Admin Action Logs",
            },
        ),
        migrations.AlterField(
            model_name="adminactionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="olestudentsubjectaccess",
            name="ole_class_level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="teachers.oleclasslevel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
