# Generated by Django 5.2.3 on 2025-07-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_adminactionlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="subscription_expires_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
