# Generated by Django 5.2.3 on 2025-07-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_customuser_subscription_expires_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationgroup",
            name="billing_cycle",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="registrationgroup",
            name="subscription_expires",
            field=models.DateField(blank=True, null=True),
        ),
    ]
