# Generated by Django 5.2.6 on 2025-09-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_registrationgroup_billing_cycle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OlePaymentVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Payment Verification",
                "verbose_name_plural": "Payment Verifications",
            },
        ),
    ]
