# Generated by Django 5.2 on 2025-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="subject",
        ),
        migrations.AddField(
            model_name="accreditedreferral",
            name="num_slots",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accreditedreferral",
            name="payment_proof",
            field=models.FileField(default=0, upload_to="payment_proofs/"),
        ),
        migrations.AddField(
            model_name="accreditedreferral",
            name="state",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name="home",
            name="num_slots",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="home",
            name="payment_proof",
            field=models.FileField(default=0, upload_to="payment_proofs/"),
        ),
        migrations.AddField(
            model_name="home",
            name="state",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name="school",
            name="num_slots",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="school",
            name="payment_proof",
            field=models.FileField(default=0, upload_to="payment_proofs/"),
        ),
        migrations.AddField(
            model_name="school",
            name="state",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
