# Generated by Django 5.2 on 2025-05-07 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_level",
                    models.CharField(
                        choices=[
                            ("JSS1", "JSS1"),
                            ("JSS2", "JSS2"),
                            ("JSS3", "JSS3"),
                            ("SSS1", "SSS1"),
                            ("SSS2", "SSS2"),
                            ("SSS3", "SSS3"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=100)),
                (
                    "question_type",
                    models.CharField(
                        choices=[("mcq", "Multiple Choice"), ("theory", "Theory")],
                        max_length=10,
                    ),
                ),
                ("text", models.TextField()),
                ("option_a", models.CharField(blank=True, max_length=255, null=True)),
                ("option_b", models.CharField(blank=True, max_length=255, null=True)),
                ("option_c", models.CharField(blank=True, max_length=255, null=True)),
                ("option_d", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "correct_answer",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("expected_answer", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="testresult",
            name="correct_answers",
        ),
        migrations.RemoveField(
            model_name="testresult",
            name="score",
        ),
        migrations.RemoveField(
            model_name="testresult",
            name="test",
        ),
        migrations.RemoveField(
            model_name="testresult",
            name="total_questions",
        ),
        migrations.AlterField(
            model_name="test",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="test",
            name="topic",
            field=models.CharField(default="General", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_option",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("theory_answer", models.TextField(blank=True, null=True)),
                ("theory_match_percentage", models.FloatField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_app.question",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="test_app.testresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "class_level",
                    models.CharField(
                        choices=[
                            ("JSS1", "JSS1"),
                            ("JSS2", "JSS2"),
                            ("JSS3", "JSS3"),
                            ("SSS1", "SSS1"),
                            ("SSS2", "SSS2"),
                            ("SSS3", "SSS3"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="testresult",
            name="test_session",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="test_app.testsession",
            ),
            preserve_default=False,
        ),
    ]
