# Generated by Django 5.2 on 2025-05-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_question_remove_testresult_correct_answers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_multiple_choice", models.BooleanField(default=True)),
                (
                    "correct_answer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
