# Generated by Django 5.2 on 2025-05-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0003_testquestion"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestQuestion",
        ),
    ]
