# Generated by Django 5.2 on 2025-05-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0004_delete_testquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="total_questions",
            field=models.IntegerField(default=0),
        ),
    ]
