# Generated by Django 5.2 on 2025-05-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0005_testresult_score_testresult_total_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsession",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
