# Generated by Django 5.2.1 on 2025-05-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0006_testsession_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="questions",
            field=models.ManyToManyField(to="test_app.question"),
        ),
    ]
