# Generated by Django 5.2.1 on 2025-05-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0007_test_questions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="questions",
        ),
    ]
