# Generated by Django 5.2.1 on 2025-05-17 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0008_remove_test_questions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="class_level",
        ),
        migrations.RemoveField(
            model_name="question",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="question",
            name="topic",
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="test_app.test",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="class_level",
            field=models.CharField(
                choices=[
                    ("JSS1", "JSS1"),
                    ("JSS2", "JSS2"),
                    ("JSS3", "JSS3"),
                    ("SSS1", "SSS1"),
                    ("SSS2", "SSS2"),
                    ("SSS3", "SSS3"),
                ],
                default="JSS1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="subject",
            field=models.CharField(default="Mathematics", max_length=100),
        ),
        migrations.AlterField(
            model_name="test",
            name="topic",
            field=models.CharField(default="Basic Science", max_length=100),
        ),
    ]
