# Generated by Django 5.2.1 on 2025-05-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_app",
            "0009_remove_question_class_level_remove_question_subject_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="subject",
            field=models.CharField(default="Mathematics", max_length=100),
        ),
    ]
