# Generated by Django 5.2.6 on 2026-04-22 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_testresult_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='subject_old',
            field=models.CharField(db_column='subject', default='Mathematics', max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='topic_old',
            field=models.CharField(db_column='topic', default='Basic Science', max_length=100),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_level', models.CharField(choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SSS1', 'SSS1'), ('SSS2', 'SSS2'), ('SSS3', 'SSS3')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'class_level')},
            },
        ),
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='test_app.subject'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='test_app.subject')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('name', 'subject')},
            },
        ),
        migrations.AlterField(
            model_name='test',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='test_app.topic'),
        ),
    ]
