# Generated by Django 5.2.6 on 2026-04-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_test_subject_old_test_topic_old_subject_and_more'),
    ]

    operations = [
    ]
