# Generated by Django 5.2.6 on 2026-04-22 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_populate_subjects_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='subject_old',
        ),
        migrations.RemoveField(
            model_name='test',
            name='topic_old',
        ),
        migrations.AddField(
            model_name='test',
            name='subject_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='test_app.subject'),
        ),
        migrations.AddField(
            model_name='test',
            name='topic_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='test_app.topic'),
        ),
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.CharField(default='Mathematics', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='topic',
            field=models.CharField(default='Basic Science', max_length=100),
        ),
    ]
