# Generated by Django 5.2.3 on 2025-06-16 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0006_olematerial_olelesson_studenttopichistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentTopicHistory",
            new_name="OleStudentTopicHistory",
        ),
        migrations.AlterField(
            model_name="studentattendancesummary",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "ole_student"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="StudentLessonSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("total_classes_attended", models.PositiveIntegerField(default=0)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "ole_student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "week_start")},
            },
        ),
    ]
