# Generated by Django 5.2.3 on 2025-06-18 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0008_teacherpayroll"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancelog",
            name="left_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="olelesson",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="olelesson",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="olelesson",
            name="is_chat_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="OleLessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_material",
                    models.FileField(
                        blank=True, null=True, upload_to="lesson_references/"
                    ),
                ),
                (
                    "class_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teachers.oleclasslevel",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teachers.olesubject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="teachers.oletopic",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="liveclasssession",
            name="lesson_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teachers.olelessonplan",
            ),
        ),
        migrations.DeleteModel(
            name="LessonPlan",
        ),
    ]
