# Generated by Django 5.2.3 on 2025-07-02 20:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0009_attendancelog_left_at_olelesson_completed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="olestudentmatch",
            unique_together={("schedule", "student")},
        ),
    ]
