# Generated by Django 5.2.3 on 2025-07-02 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0010_alter_olestudentmatch_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="olestudentmatch",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="olestudentmatch",
            constraint=models.UniqueConstraint(
                fields=("schedule", "student"), name="unique_schedule_student_match"
            ),
        ),
    ]
