# Generated by Django 5.2.3 on 2025-07-02 22:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0011_alter_olestudentmatch_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="olestudentmatch",
            name="unique_schedule_student_match",
        ),
        migrations.AlterUniqueTogether(
            name="olestudentmatch",
            unique_together={("schedule", "student")},
        ),
    ]
